name: GabrielNadeau
favicon: null
layout_spectrum: 0.7366203749552369
typography_spectrum: 0.4140552047174424
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0909'
    - '#fafafa'
    - '#515b58'
    - '#798e92'
    - '#b21f1c'
  brandStrength: 0.375
  lightness: 0.05032169003970921
  saturation: 0.3075255253352225
  rhythmicContrast: 0.15112868743017316
purpose: []
