name: GabrielNadeau
favicon: null
layout_spectrum: 0.23692
typography_spectrum: 0.7333
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38384639-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbd7d6'
    - '#938b80'
    - '#030207'
    - '#4d3200'
    - '#6a5d38'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
