name: GabrielNadeau
favicon: null
layout_spectrum: 0.90399
typography_spectrum: 0.7199
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38384639-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0909'
    - '#fafafa'
    - '#515b58'
    - '#798e92'
    - '#b21f1c'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
